version: '3'
services:
  pgadmin:
    container_name: pgadmin
    environment:
      - POSTGRES_USER=node_gmp
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=node_gmp
      - PGADMIN_DEFAULT_EMAIL=username@user.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    restart: unless-stopped
    volumes:
      - pgadmin:/root/.pgadmin

volumes:
  pgadmin: {}