export const ANDORRA_HOLIDAYS = [
    {
        date: '2024-01-01',
        localName: 'Any nou',
        name: "New Year's Day",
        countryCode: 'AD',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-01-06',
        localName: 'Reis',
        name: 'Epiphany',
        countryCode: 'AD',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-02-12',
        localName: 'Carnaval',
        name: 'Carnival',
        countryCode: 'AD',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-03-14',
        localName: 'Dia de la Constitució',
        name: 'Constitution Day',
        countryCode: 'AD',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-03-29',
        localName: 'Divendres Sant',
        name: 'Good Friday',
        countryCode: 'AD',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-04-01',
        localName: 'Dilluns de Pasqua',
        name: 'Easter Monday',
        countryCode: 'AD',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-05-01',
        localName: 'Festa del Treball',
        name: 'Labour Day',
        countryCode: 'AD',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-05-20',
        localName: 'Dilluns de Pentecosta',
        name: 'Whit Monday',
        countryCode: 'AD',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-08-15',
        localName: 'Assumpció',
        name: 'Assumption Day',
        countryCode: 'AD',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-09-08',
        localName: 'Mare de Déu de Meritxell',
        name: 'National Holiday',
        countryCode: 'AD',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-11-01',
        localName: 'Tots Sants',
        name: "All Saints' Day",
        countryCode: 'AD',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-12-08',
        localName: 'Immaculada Concepció',
        name: 'Immaculate Conception',
        countryCode: 'AD',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-12-25',
        localName: 'Nadal',
        name: 'Christmas Day',
        countryCode: 'AD',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-12-26',
        localName: 'Sant Esteve',
        name: "St. Stephen's Day",
        countryCode: 'AD',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
];

export const ANDORRA_SHORTEN_HOLIDAYS = [
    { name: "New Year's Day", localName: 'Any nou', date: '2024-01-01' },
    { name: 'Epiphany', localName: 'Reis', date: '2024-01-06' },
    { name: 'Carnival', localName: 'Carnaval', date: '2024-02-12' },
    {
        name: 'Constitution Day',
        localName: 'Dia de la Constitució',
        date: '2024-03-14',
    },
    {
        name: 'Good Friday',
        localName: 'Divendres Sant',
        date: '2024-03-29',
    },
    {
        name: 'Easter Monday',
        localName: 'Dilluns de Pasqua',
        date: '2024-04-01',
    },
    {
        name: 'Labour Day',
        localName: 'Festa del Treball',
        date: '2024-05-01',
    },
    {
        name: 'Whit Monday',
        localName: 'Dilluns de Pentecosta',
        date: '2024-05-20',
    },
    {
        name: 'Assumption Day',
        localName: 'Assumpció',
        date: '2024-08-15',
    },
    {
        name: 'National Holiday',
        localName: 'Mare de Déu de Meritxell',
        date: '2024-09-08',
    },
    {
        name: "All Saints' Day",
        localName: 'Tots Sants',
        date: '2024-11-01',
    },
    {
        name: 'Immaculate Conception',
        localName: 'Immaculada Concepció',
        date: '2024-12-08',
    },
    { name: 'Christmas Day', localName: 'Nadal', date: '2024-12-25' },
    {
        name: "St. Stephen's Day",
        localName: 'Sant Esteve',
        date: '2024-12-26',
    },
];

export const GB_NEXT_HOLIDAYS = [
    {
        date: '2024-03-17',
        localName: "Saint Patrick's Day",
        name: "Saint Patrick's Day",
        countryCode: 'GB',
        fixed: false,
        global: false,
        counties: ['GB-NIR'],
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-03-29',
        localName: 'Good Friday',
        name: 'Good Friday',
        countryCode: 'GB',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-04-01',
        localName: 'Easter Monday',
        name: 'Easter Monday',
        countryCode: 'GB',
        fixed: false,
        global: false,
        counties: ['GB-ENG', 'GB-WLS', 'GB-NIR'],
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-05-06',
        localName: 'Early May Bank Holiday',
        name: 'Early May Bank Holiday',
        countryCode: 'GB',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-05-27',
        localName: 'Spring Bank Holiday',
        name: 'Spring Bank Holiday',
        countryCode: 'GB',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-07-12',
        localName: 'Battle of the Boyne',
        name: 'Battle of the Boyne',
        countryCode: 'GB',
        fixed: false,
        global: false,
        counties: ['GB-NIR'],
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-08-05',
        localName: 'Summer Bank Holiday',
        name: 'Summer Bank Holiday',
        countryCode: 'GB',
        fixed: false,
        global: false,
        counties: ['GB-SCT'],
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-08-26',
        localName: 'Summer Bank Holiday',
        name: 'Summer Bank Holiday',
        countryCode: 'GB',
        fixed: false,
        global: false,
        counties: ['GB-ENG', 'GB-WLS', 'GB-NIR'],
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-11-30',
        localName: "Saint Andrew's Day",
        name: "Saint Andrew's Day",
        countryCode: 'GB',
        fixed: false,
        global: false,
        counties: ['GB-SCT'],
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-12-25',
        localName: 'Christmas Day',
        name: 'Christmas Day',
        countryCode: 'GB',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2024-12-26',
        localName: 'Boxing Day',
        name: "St. Stephen's Day",
        countryCode: 'GB',
        fixed: false,
        global: true,
        counties: null,
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2025-01-01',
        localName: "New Year's Day",
        name: "New Year's Day",
        countryCode: 'GB',
        fixed: false,
        global: false,
        counties: ['GB-NIR'],
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2025-01-01',
        localName: "New Year's Day",
        name: "New Year's Day",
        countryCode: 'GB',
        fixed: false,
        global: false,
        counties: ['GB-ENG', 'GB-WLS'],
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2025-01-01',
        localName: "New Year's Day",
        name: "New Year's Day",
        countryCode: 'GB',
        fixed: false,
        global: false,
        counties: ['GB-SCT'],
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2025-01-02',
        localName: '2 January',
        name: '2 January',
        countryCode: 'GB',
        fixed: false,
        global: false,
        counties: ['GB-SCT'],
        launchYear: null,
        types: ['Public'],
    },
    {
        date: '2025-03-17',
        localName: "Saint Patrick's Day",
        name: "Saint Patrick's Day",
        countryCode: 'GB',
        fixed: false,
        global: false,
        counties: ['GB-NIR'],
        launchYear: null,
        types: ['Public'],
    },
];

export const GB_NEXT_HOLIDAYS_RESULT = [
    {
      name: "Saint Patrick's Day",
      localName: "Saint Patrick's Day",
      date: '2024-03-17'
    },
    { name: 'Good Friday', localName: 'Good Friday', date: '2024-03-29' },
    {
      name: 'Easter Monday',
      localName: 'Easter Monday',
      date: '2024-04-01'
    },
    {
      name: 'Early May Bank Holiday',
      localName: 'Early May Bank Holiday',
      date: '2024-05-06'
    },
    {
      name: 'Spring Bank Holiday',
      localName: 'Spring Bank Holiday',
      date: '2024-05-27'
    },
    {
      name: 'Battle of the Boyne',
      localName: 'Battle of the Boyne',
      date: '2024-07-12'
    },
    {
      name: 'Summer Bank Holiday',
      localName: 'Summer Bank Holiday',
      date: '2024-08-05'
    },
    {
      name: 'Summer Bank Holiday',
      localName: 'Summer Bank Holiday',
      date: '2024-08-26'
    },
    {
      name: "Saint Andrew's Day",
      localName: "Saint Andrew's Day",
      date: '2024-11-30'
    },
    {
      name: 'Christmas Day',
      localName: 'Christmas Day',
      date: '2024-12-25'
    },
    {
      name: "St. Stephen's Day",
      localName: 'Boxing Day',
      date: '2024-12-26'
    },
    {
      name: "New Year's Day",
      localName: "New Year's Day",
      date: '2025-01-01'
    },
    {
      name: "New Year's Day",
      localName: "New Year's Day",
      date: '2025-01-01'
    },
    {
      name: "New Year's Day",
      localName: "New Year's Day",
      date: '2025-01-01'
    },
    { name: '2 January', localName: '2 January', date: '2025-01-02' },
    {
      name: "Saint Patrick's Day",
      localName: "Saint Patrick's Day",
      date: '2025-03-17'
    }
  ]